[tool.poetry]
name = "weld-deps"
version = "0.6.0"
description = ""
authors = ["edayot"]
license = "mit"

[tool.poetry.dependencies]
python = "^3.11"
smithed = ">=0.16.0"
beet=">=0.104.1"
requests = "^2.31.0"
semver = "^3.0.2"
black = "^23.12.1"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
